### PR TITLE
Add travis and dockerfile

### PR DESCRIPTION
**Pull request by emmyni**

### CODE REVIEW

**Comment by priyasiddharth** [comment]
Emmy,

This has changes other than travis and dockerfile... is this intended?

**Comment by emmyni** [comment]
I tried to rebase the commits into 1 commit, but I did something wrong and it added some of the changes other people have made recently. I'm not sure how to fix it right now. I tried making a brand new branch with just the 2 files that I added, but it showed all the past commits as well. Do you know what I can do to fix this?

**Comment by emmyni** [comment]
> Emmy,
> 
> This has changes other than travis and dockerfile... is this intended?

**Comment by priyasiddharth** [comment]
There may be multiple ways to fix this... One way is to start with a clean branch (which matches master) and "cherry-pick" the commit(s) you want onto that branch.

See.
https://stackoverflow.com/questions/9339429/what-does-cherry-picking-a-commit-with-git-mean

**Pull request closed without merging**
